{% set name = "globus-sdk" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/globus/globus-sdk-python/archive/{{ version }}.tar.gz
  sha256: 71655f3a4210b8a5b3bf8a51491e6b24f78cdaa64b7b17d857d2c168b47b0d88

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    # we need cryptography and will use the run constraints from pyjwt
    - cryptography
    - pyjwt >=2.0.0,<3.0.0
    - requests >=2.9.2,<3.0.0

test:
  imports:
    - globus_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/globus/globus-sdk-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Globus SDK for Python
  description: This SDK provides a convenient Pythonic interface to Globus APIs.
  doc_url: http://globus-sdk-python.readthedocs.io/
  dev_url: https://github.com/globus/globus-sdk-python

extra:
  recipe-maintainers:
    - xylar
    - lukaszlacinski
