travis:
  secure:
    BINSTAR_TOKEN: uLnUzjKqWPpcj5tk+M2zdMA2qNAwdv7Z+oj4u9TDz+yCNkpcr4bOdq+uhIF10F12cmfT5uu40pQnbrXUI050R0cu8kZZMOp4IvyA5dD1dDXI7iSqeYwe446mkqU8KKcbUniCalDdohcR9J9MabUyswM/M9BceAPB4ANVWDZP7ki6GpzclDhUIyU92E1VPNjd3IvQm+qwXdULz/xRqJ045/8fVGckBfyUZx/Rzi//JPq7yju+kAfY7WFD6JljEWlo9VLQOYEeeTwd7OUoEg2R1HD9R9qQ75+eaersXFh9oJrvGNHTEmKMVyjBjreFg20te8nVVwLAszhrzv+wHjkf2FtbUa4wxw0+0wfDtZOzvLyuixft+A/Jeqero3iNvrSWzfNYv5ZwFxhG7b94Uk0ZyJrQTIL5gBn+IKJMbl1ZqovtE/qR8aJ4SKlX0KSbM43abDxZMDAJ0GFzI4yA5WrVQqPwOGH59zcSrqkH3jXfqPBoiHP1dUHH1OQE0xIpTqKZYRQkvfLroOqifmQV0YxnMZm4k6qPxzcimJVWkFxVnUOCdq8oivIwj0Mqj+EGIMiC3LP6WPIpqAFi89w7a34LZNibdGi7LyyBoXfyROBjEegOquvPQ5SrvUDqvLH6DzztPWKu9lwwmZU/S4dfsbZAwYCfg5T0jNnlvJxIA+7rQZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
